let sb,session,products=[],cart={},profile,wallet,adminTopupChannel;
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const money=v=>`${Number(v||0).toFixed(2)} د.ل`;
const el=id=>document.getElementById(id);
let authBusy=false;
async function boot(){
 try{
  sb=await loadSupabase();
  if(window.__LIBYAN_RECOVERY_ACTIVE)return;
  const r=await sb.auth.getSession();
  session=r.data.session||null;
  if(session) await loadStore(); else renderLogin();
  sb.auth.onAuthStateChange(async(event,nextSession)=>{
   if(event==='SIGNED_OUT'){session=null;cart={};if(adminTopupChannel){await sb.removeChannel(adminTopupChannel);adminTopupChannel=null}renderLogin();}
  });
 }catch(e){app.innerHTML=`<div class="card" style="text-align:center;margin-top:30px"><h1>⚡ Libyan Store</h1><p class="muted">${esc(e.message||'تعذر تشغيل تسجيل الدخول')}</p><button class="btn primary" onclick="location.reload()">إعادة المحاولة</button></div>`}
}
function renderLogin(msg=''){app.innerHTML=`<div style="max-width:430px;margin:35px auto;text-align:center"><div style="font-size:48px">⚡</div><h1>Libyan Store</h1><p class="muted">اشتراكات رقمية ومحفظة وتسليم أكواد</p><div class="card" style="display:grid;gap:10px;text-align:right"><input id="email" class="field" type="email" placeholder="البريد الإلكتروني"><input id="pass" class="field" type="password" placeholder="كلمة المرور"><button class="btn primary" id="login">دخول</button><button class="btn" id="signup">إنشاء حساب</button><button class="btn" id="forgot">نسيت كلمة المرور؟</button><small id="msg" class="muted">${esc(msg)}</small></div></div>`;el('login').onclick=()=>auth(false);el('signup').onclick=()=>auth(true);el('forgot').onclick=resetPassword}
async function resetPassword(){const email=el('email').value.trim(),msg=el('msg');if(!email)return msg.textContent='اكتب بريدك الإلكتروني أولاً';msg.textContent='جارٍ إرسال رابط الاستعادة...';try{const r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(r.error)return msg.textContent=r.error.message;msg.textContent='تم إرسال رابط تغيير كلمة المرور إلى بريدك. افتح الرابط من نفس الجهاز.'}catch(e){msg.textContent=e.message||'تعذر إرسال رابط الاستعادة'}}
async function notifyLoginToDiscord(){try{const r=await sb.functions.invoke('discord-notify',{body:{type:'login',id:session.user.id}});if(r.error)console.log('Discord login notification error:',r.error);else console.log('Discord login notification sent:',r.data)}catch(e){console.log('Discord login notification:',e)}}
async function auth(signup){
 if(authBusy)return;
 const msg=el('msg'),button=signup?el('signup'):el('login');
 const email=emailInput(),password=el('pass').value.trim();
 if(!email)return msg.textContent='اكتب البريد الإلكتروني أولاً';
 if(password.length<6)return msg.textContent='كلمة المرور يجب أن تكون 6 أحرف على الأقل';
 authBusy=true;msg.textContent=signup?'جارٍ إنشاء الحساب...':'جارٍ تسجيل الدخول...';if(button)button.disabled=true;
 try{
  const r=signup?await sb.auth.signUp({email,password}):await sb.auth.signInWithPassword({email,password});
  if(r.error){msg.textContent=humanAuthError(r.error);return;}
  if(signup&&!r.data.session){msg.textContent='تم إنشاء الحساب. افتح بريدك الإلكتروني لتأكيد الحساب، ثم سجّل الدخول.';return;}
  session=r.data.session;
  if(!session){msg.textContent='تعذر إنشاء جلسة تسجيل الدخول. حاول مرة أخرى.';return;}
  if(!signup)notifyLoginToDiscord();
  await loadStore();
 }catch(e){msg.textContent=humanAuthError(e)}finally{authBusy=false;if(button)button.disabled=false}
}
function humanAuthError(e){
 const m=String(e?.message||e||'تعذر تنفيذ العملية');
 if(/invalid login credentials/i.test(m))return 'البريد الإلكتروني أو كلمة المرور غير صحيحة.';
 if(/email not confirmed/i.test(m))return 'الحساب غير مؤكد. افتح رسالة التأكيد في بريدك الإلكتروني ثم حاول تسجيل الدخول.';
 if(/user already registered/i.test(m))return 'هذا البريد مسجل بالفعل. استخدم تسجيل الدخول بدل إنشاء حساب.';
 if(/password.*(weak|at least)/i.test(m))return 'كلمة المرور ضعيفة. استخدم 6 أحرف على الأقل.';
 if(/rate limit|too many requests/i.test(m))return 'تم تجاوز عدد المحاولات مؤقتًا. انتظر قليلًا ثم حاول مرة أخرى.';
 return m;
}
function emailInput(){return el('email').value.trim()}
async function loadStore(){const uid=session.user.id;const [p,w,pr]=await Promise.all([sb.from('profiles').select('full_name,phone,role').eq('id',uid).single(),sb.from('wallets').select('balance').eq('user_id',uid).single(),sb.from('products').select('id,name,description,category,price,currency,product_codes(status)').eq('active',true).order('created_at')]);profile=p.data;wallet=w.data;products=(pr.data||[]).map(p=>({...p,stock_count:(p.product_codes||[]).filter(c=>c.status==='available').length}));renderStore();startAdminTopupRealtime()}
function startAdminTopupRealtime(){if(profile?.role!=='admin'||!sb)return;if(adminTopupChannel){sb.removeChannel(adminTopupChannel);adminTopupChannel=null}adminTopupChannel=sb.channel('admin-wallet-topups').on('postgres_changes',{event:'INSERT',schema:'public',table:'wallet_topups'},payload=>{const row=payload.new;if(row?.status==='pending')showTopupNotification(row)}).subscribe(status=>{if(status!=='SUBSCRIBED')console.log('Topup realtime status:',status)})}
function showTopupNotification(row){const old=document.getElementById('topupToast');if(old)old.remove();const toast=document.createElement('div');toast.id='topupToast';toast.dir='rtl';toast.style.cssText='position:fixed;top:18px;right:18px;z-index:99999;max-width:360px;background:#17100c;border:1px solid #ff7a18;box-shadow:0 12px 35px rgba(0,0,0,.45);border-radius:16px;padding:15px;color:#fff;font-family:inherit';toast.innerHTML=`<div style="font-size:18px;font-weight:800">🔔 طلب تعبئة رصيد جديد</div><div style="margin-top:8px;color:#ffd9bd">المبلغ: <b>${money(row.amount)}</b></div><div style="margin-top:3px;color:#ffd9bd">الطريقة: <b>${esc(row.method)}</b></div><div style="margin-top:3px;color:#ffd9bd">رقم المحوّل: <b>${esc(row.sender_phone||'غير متوفر')}</b></div><button class="btn primary" id="closeTopupToast" style="width:100%;margin-top:12px">فتح طلبات الشحن</button>`;document.body.appendChild(toast);el('closeTopupToast').onclick=()=>{toast.remove();const adminBtn=document.querySelector('[data-view="admin"]');if(adminBtn)adminBtn.click()};try{const Ctx=window.AudioContext||window.webkitAudioContext;if(Ctx){const ctx=new Ctx(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=880;gain.gain.value=.05;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.18);setTimeout(()=>ctx.close(),300)}}catch(e){}if('Notification'in window&&Notification.permission==='granted'){try{new Notification('طلب تعبئة رصيد جديد',{body:`${money(row.amount)} — ${row.method}`})}catch(e){}}}
function renderStore(){
  app.innerHTML=`<div class="shell"><header class="topbar"><div><b style="font-size:22px">⚡ Libyan Store</b><div class="muted">${esc(profile?.full_name||session.user.email||session.user.phone||'')}</div></div><button class="btn" id="logout">خروج</button></header><section class="card" style="margin:15px 0;background:#24150f;border-color:#5a3020"><span class="accent">رصيد المحفظة</span><strong style="display:block;font-size:30px;margin-top:4px">${money(wallet?.balance)}</strong></section><div id="view"></div><nav class="nav"><div class="nav-inner"><button class="active" data-view="store">🛍️ المتجر</button><button data-view="cart">🛒 السلة</button><button data-view="wallet">💰 المحفظة</button><button data-view="orders">📦 طلباتي</button><button data-view="account">👤 حسابي</button>${profile?.role==='admin'?'<button data-view="admin">⚙️ الإدارة</button>':''}</div></nav></div>`;
  el('logout').onclick=async()=>{if(adminTopupChannel){await sb.removeChannel(adminTopupChannel);adminTopupChannel=null}await sb.auth.signOut();session=null;cart={};renderLogin()};
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');({store:renderProducts,cart:renderCartPage,wallet:renderWallet,orders:renderOrders,account:renderAccount,admin:renderAdmin}[b.dataset.view])()});
  renderProducts();
}
function renderCartPage(){
  const entries=Object.entries(cart).filter(([id,q])=>Number(q)>0&&products.some(p=>p.id===id));
  let total=0;
  const rows=entries.map(([id,q])=>{const p=products.find(x=>x.id===id);const t=Number(p.price)*Number(q);total+=t;return `<div style="padding:12px 0;border-bottom:1px solid #202b3a"><div style="display:flex;justify-content:space-between"><div><b>${esc(p.name)}</b><div class="muted">${money(p.price)} × ${q}</div></div><b>${money(t)}</b></div><div style="display:flex;gap:7px;margin-top:8px"><button class="btn" data-minus="${p.id}">−</button><span class="pill">${q}</span><button class="btn" data-plus="${p.id}">+</button><button class="btn" data-remove="${p.id}" style="margin-right:auto">🗑️ إزالة</button></div></div>`}).join('');
  el('view').innerHTML=entries.length?`<h2>🛒 السلة</h2><div class="card">${rows}<hr style="border-color:#263345"><b>الإجمالي: ${money(total)}</b><button class="btn primary" id="pageBuy" style="width:100%;margin-top:12px">شراء من المحفظة</button></div>`:'<div class="card" style="text-align:center"><h2>🛒 السلة فارغة</h2><p class="muted">أضف منتجًا من المتجر ليظهر هنا.</p></div>';
  document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>{const id=b.dataset.plus;cart[id]=(cart[id]||0)+1;renderCartPage()});
  document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>{const id=b.dataset.minus;if((cart[id]||0)>1)cart[id]--;else delete cart[id];renderCartPage()});
  document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{delete cart[b.dataset.remove];renderCartPage()});
  if(el('pageBuy'))el('pageBuy').onclick=checkout;
}
function renderProducts(){el('view').innerHTML=`<div class="topbar"><h2>المنتجات</h2><span class="pill">${products.length} منتج</span></div><div class="grid">${products.map(p=>`<article class="card"><span class="pill">${esc(p.category||'رقمي')}</span><h3>${esc(p.name)}</h3><p class="muted">${esc(p.description||'')}</p><strong class="accent">${money(p.price)}</strong>${p.stock_count>0?`<button class="btn light" style="display:block;width:100%;margin-top:12px" data-add="${p.id}">أضف للسلة</button>`:`<div class="pill" style="display:block;text-align:center;margin-top:12px;padding:10px;color:#ffb4b4;border-color:#6b3030">نفد المخزون</div>`}</article>`).join('')}</div><div id="cartBox" style="margin-top:15px"></div>`;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===b.dataset.add);if(!p||p.stock_count<1)return;cart[b.dataset.add]=Math.min((cart[b.dataset.add]||0)+1,p.stock_count);renderCart()});renderCart()}
function renderCart(){
  const entries=Object.entries(cart).filter(([id,q])=>Number(q)>0&&products.some(p=>p.id===id));
  const badge=el('cartCount');
  const navBadge=el('navCartCount');
  const count=entries.reduce((sum,[id,q])=>sum+Number(q),0);
  if(badge)badge.textContent=count;
  if(navBadge)navBadge.textContent=count;
  const box=el('cartBox');
  if(!box)return;
  if(!entries.length){
    box.innerHTML='<div class="card"><h3>🛒 السلة <span class="pill">0</span></h3><p class="muted">السلة فارغة</p></div>';
    return;
  }
  let total=0;
  const rows=entries.map(([id,q])=>{
    const p=products.find(x=>x.id===id);
    const itemTotal=Number(p.price)*Number(q);
    total+=itemTotal;
    return `<div style="padding:12px 0;border-bottom:1px solid #202b3a"><div style="display:flex;justify-content:space-between;gap:10px"><div><b>${esc(p.name)}</b><div class="muted">${money(p.price)} × ${q}</div></div><b>${money(itemTotal)}</b></div><div style="display:flex;gap:7px;margin-top:9px"><button class="btn" data-minus="${p.id}">−</button><span class="pill">${q}</span><button class="btn" data-plus="${p.id}">+</button><button class="btn" data-remove="${p.id}" style="margin-right:auto">🗑️ إزالة</button></div></div>`;
  }).join('');
  box.innerHTML=`<div class="card"><div class="topbar"><h3>🛒 السلة</h3><span class="pill">${count} منتج</span></div>${rows}<hr style="border-color:#263345"><b>الإجمالي: ${money(total)}</b><button class="btn primary" id="buy" style="width:100%;margin-top:12px">شراء من المحفظة</button></div>`;
  document.querySelectorAll('[data-plus]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.plus,p=products.find(x=>x.id===id);if(!p||p.stock_count<1)return;cart[id]=Math.min((cart[id]||0)+1,p.stock_count);renderCart()});
  document.querySelectorAll('[data-minus]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.minus;if((cart[id]||0)>1)cart[id]--;else delete cart[id];renderCart()});
  document.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=()=>{delete cart[btn.dataset.remove];renderCart()});
  el('buy').onclick=checkout;
}async function checkout(){
 const name=(profile?.full_name||session.user.email||'عميل').trim();const phone=(profile?.phone||session.user.phone||'').trim();
 const items=Object.entries(cart).map(([product_id,quantity])=>({product_id,quantity}));
 const r=await sb.rpc('create_wallet_order',{p_items:items,p_customer_name:name,p_customer_phone:phone});if(r.error)return alert(r.error.message);
 const orderId=r.data;cart={};await loadStore();
 const codesResult=await sb.rpc('get_my_order_codes',{p_order_id:orderId});if(codesResult.error)return alert(codesResult.error.message);
 const codes=codesResult.data||[],grouped={};codes.forEach(x=>{(grouped[x.product_id]??=[]).push(x.code)});
 let sections='';Object.entries(grouped).forEach(([productId,productCodes])=>{const p=products.find(x=>x.id===productId);sections+='<div style="margin-top:14px"><div style="font-weight:800;font-size:16px">📦 '+esc(p?.name||'المنتج')+'</div>';productCodes.forEach(code=>{sections+='<div style="margin-top:8px;padding:13px;background:#0a1017;border:1px solid #263345;border-radius:10px;font-family:monospace;word-break:break-all;direction:ltr;text-align:left;user-select:text">'+esc(code)+'</div>'});sections+='</div>';});
 el('view').innerHTML='<div class="card" style="border-color:#2f6b45;background:#101c16"><div style="font-size:24px">🎉</div><h2 style="margin:6px 0">تم الشراء بنجاح</h2><p class="muted">بيانات منتجاتك جاهزة الآن وتظهر أمامك مباشرة.</p>'+ (sections||'<p class="muted">تم الشراء، لكن لم يتم العثور على بيانات المنتج.</p>') +'<button class="btn primary" id="ordersAfterBuy" style="width:100%;margin-top:16px">📦 عرض طلباتي</button></div>';
 el('ordersAfterBuy').onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));const b=document.querySelector('[data-view="orders"]');if(b)b.classList.add('active');renderOrders()};
}
async function renderAccount(){
  const current=profile||{};
  el('view').innerHTML=`<div class="card"><h2>👤 حسابي</h2><label>الاسم الكامل</label><input id="accountName" class="field" style="margin-top:6px" value="${esc(current.full_name||'')}" placeholder="الاسم الكامل"><label style="display:block;margin-top:10px">رقم الهاتف</label><input id="accountPhone" class="field" style="margin-top:6px" value="${esc(current.phone||session.user.phone||'')}" placeholder="رقم الهاتف"><p class="muted" style="margin-top:10px">البريد: ${esc(session.user.email||'غير مرتبط')}</p><button class="btn primary" id="saveAccount" style="width:100%;margin-top:10px">حفظ البيانات</button><small id="accountMsg" class="muted" style="display:block;margin-top:8px"></small></div>`;
  el('saveAccount').onclick=async()=>{const full_name=el('accountName').value.trim(),phone=el('accountPhone').value.trim();if(!full_name)return el('accountMsg').textContent='أدخل الاسم';const r=await sb.from('profiles').update({full_name,phone}).eq('id',session.user.id);if(r.error)return el('accountMsg').textContent=r.error.message;profile={...profile,full_name,phone};el('accountMsg').textContent='تم حفظ البيانات بنجاح.';};
}
async function renderWallet(){const r=await sb.from('wallet_topups').select('id,amount,method,status,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(20);const settings=await sb.from('store_settings').select('key,value').in('key',['libyana_number','almadar_number']);const nums=Object.fromEntries((settings.data||[]).map(x=>[x.key,x.value]));el('view').innerHTML=`<div class="card"><h2>💰 شحن المحفظة</h2><p class="muted">حوّل المبلغ إلى الرقم الظاهر ثم أرسل الطلب للمراجعة.</p><p>ليبيانا: <b>${esc(nums.libyana_number||'غير محدد')}</b><br>المدار: <b>${esc(nums.almadar_number||'غير محدد')}</b></p><select id="tm" class="field"><option value="libyana">ليبيانا</option><option value="almadar">المدار</option></select><input id="ta" class="field" style="margin-top:8px" type="number" min="1" placeholder="المبلغ بالدينار"><input id="tp" class="field" style="margin-top:8px" placeholder="رقم الهاتف المحوّل منه"><button class="btn primary" id="sendTop" style="width:100%;margin-top:10px">إرسال طلب الشحن</button></div><div class="card" style="margin-top:12px"><h3>طلبات الشحن</h3>${(r.data||[]).map(x=>`<div style="padding:9px 0;border-bottom:1px solid #202b3a">${money(x.amount)} — ${esc(x.method)} — <span class="pill">${esc(x.status)}</span></div>`).join('')||'<span class="muted">لا توجد طلبات</span>'}</div>`;el('sendTop').onclick=async()=>{const amount=Number(el('ta').value);if(!(amount>0)||!el('tp').value.trim())return alert('أكمل البيانات');const x=await sb.rpc('create_wallet_topup',{p_amount:amount,p_method:el('tm').value,p_sender_phone:el('tp').value.trim()});if(x.error)return alert(x.error.message);let notifyFailed=false;try{const n=await sb.functions.invoke('discord-notify',{body:{type:'topup',id:x.data.id}});if(n.error){notifyFailed=true;console.warn('Discord topup notification error:',n.error);let detail=n.error.message||String(n.error);try{if(n.error.context){const rr=await n.error.context.clone().text();if(rr)detail+=' | '+rr}}catch{}alert('تم إرسال طلب الشحن، لكن تعذر إرسال إشعار Discord: '+detail)}else console.log('Discord topup notification sent:',n.data)}catch(e){notifyFailed=true;console.warn('Discord topup notification failed:',e);alert('تم إرسال طلب الشحن، لكن تعذر إرسال إشعار Discord')}if(!notifyFailed)alert('تم إرسال طلب الشحن');renderWallet()}}
async function renderOrders(){const r=await sb.from('orders').select('id,total,status,created_at').eq('user_id',session.user.id).order('created_at',{ascending:false}).limit(30);let html='';for(const o of r.data||[]){const c=await sb.rpc('get_my_order_codes',{p_order_id:o.id});const codes=c.data||[];const grouped={};codes.forEach(x=>{(grouped[x.product_id]??=[]).push(x.code)});const productSections=Object.entries(grouped).map(([productId,codesForProduct])=>{const p=products.find(x=>x.id===productId);return `<div style="margin-top:10px"><b>📦 ${esc(p?.name||'المنتج')}</b>${codesForProduct.map(code=>`<div style="margin-top:7px;padding:11px;background:#0a1017;border-radius:9px;font-family:monospace;word-break:break-all;direction:ltr;text-align:left">${esc(code)}</div>`).join('')}</div>`}).join('');html+=`<article class="card" style="margin-bottom:10px"><div class="topbar"><b>${money(o.total)}</b><span class="pill">${esc(o.status)}</span></div><div class="muted">${new Date(o.created_at).toLocaleString('ar-LY')}</div>${productSections||'<div class="muted" style="margin-top:10px">لا توجد أكواد مرتبطة بهذا الطلب.</div>'}</article>`}el('view').innerHTML=`<h2>📦 طلباتي</h2>${html||'<div class="card muted">لا توجد طلبات بعد.</div>'}`}
async function renderAdmin(){if(profile?.role!=='admin')return;const [pr,top,orders,codes,settings]=await Promise.all([sb.from('products').select('*').order('created_at',{ascending:false}),sb.from('wallet_topups').select('*').order('created_at',{ascending:false}).limit(50),sb.from('orders').select('*').order('created_at',{ascending:false}).limit(50),sb.from('product_codes').select('id,product_id,code,status,order_id').order('created_at',{ascending:false}).limit(200),sb.from('store_settings').select('key,value').in('key',['libyana_number','almadar_number'])]);
 const plist=pr.data||[]; const clist=codes.data||[]; const counts={};clist.forEach(c=>counts[c.product_id]=(counts[c.product_id]||0)+1);
 el('view').innerHTML=`<div class="topbar"><h2>⚙️ لوحة الإدارة</h2><span class="pill">مدير</span></div><div class="grid">
 <div class="card"><h3>➕ إضافة منتج</h3><input id="pn" class="field" placeholder="اسم المنتج"><input id="pc" class="field" style="margin-top:8px" placeholder="التصنيف"><input id="pp" class="field" style="margin-top:8px" type="number" min="0" step="0.01" placeholder="السعر بالدينار"><textarea id="pd" class="field" style="margin-top:8px;min-height:80px" placeholder="وصف المنتج"></textarea><button class="btn primary" id="addProduct" style="width:100%;margin-top:10px">إضافة المنتج</button></div>
 <div class="card"><h3>📦 المنتجات</h3>${plist.map(p=>`<div style="padding:10px 0;border-bottom:1px solid #202b3a"><b>${esc(p.name)}</b><div class="muted">${money(p.price)} — ${esc(p.category||'رقمي')} — ${counts[p.id]||0} كود</div><div style="margin-top:7px"><button class="btn" data-edit-product="${p.id}">تعديل</button> <button class="btn" data-toggle-product="${p.id}" data-active="${p.active}">${p.active?'إيقاف':'تفعيل'}</button></div></div>`).join('')||'<span class="muted">لا توجد منتجات</span>'}</div>
 <div class="card"><h3>🔑 إضافة أكواد</h3><select id="codeProduct" class="field">${plist.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><textarea id="codesText" class="field" style="margin-top:8px;min-height:150px" placeholder="ضع كل كود في سطر مستقل"></textarea><button class="btn primary" id="addCodes" style="width:100%;margin-top:10px">حفظ الأكواد</button><small id="codeMsg" class="muted" style="display:block;margin-top:8px"></small></div>
 <div class="card"><h3>🧾 مخزون الأكواد</h3>${clist.slice(0,100).map(c=>{const p=plist.find(x=>x.id===c.product_id);return `<div style="padding:7px 0;border-bottom:1px solid #202b3a"><div style="font-family:monospace">${esc(c.code)}</div><span class="muted">${esc(p?.name||'منتج محذوف')} — ${esc(c.status)}</span>${c.status==='available'?` <button class="btn" data-delete-code="${c.id}" style="float:left">حذف</button>`:''}</div>`}).join('')||'<span class="muted">لا توجد أكواد. أضف أكواد من البطاقة السابقة.</span>'}</div>
 <div class="card"><h3>📲 أرقام الشحن</h3><input id="libyanaNum" class="field" value="${esc((settings.data||[]).find(x=>x.key==='libyana_number')?.value||'')}" placeholder="رقم ليبيانا"><input id="almadarNum" class="field" style="margin-top:8px" value="${esc((settings.data||[]).find(x=>x.key==='almadar_number')?.value||'')}" placeholder="رقم المدار"><button class="btn primary" id="saveNumbers" style="width:100%;margin-top:10px">حفظ أرقام الشحن</button></div>
 <div class="card"><h3>💳 طلبات الشحن</h3>${(top.data||[]).map(t=>`<div style="padding:8px 0;border-bottom:1px solid #202b3a">${money(t.amount)} — ${esc(t.method)} — ${esc(t.sender_phone||'')}<br><span class="pill">${esc(t.status)}</span>${t.status==='pending'?`<div style="margin-top:7px"><button class="btn primary" data-approve="${t.id}">اعتماد</button> <button class="btn" data-reject="${t.id}">رفض</button></div>`:''}</div>`).join('')||'<span class="muted">لا توجد طلبات</span>'}</div>
 <div class="card"><h3>🛒 الطلبات</h3>${(orders.data||[]).map(o=>`<div style="padding:8px 0;border-bottom:1px solid #202b3a">${money(o.total)} — <span class="pill">${esc(o.status)}</span><br><span class="muted">${esc(o.customer_name||'')} — ${esc(o.customer_phone||'')}</span></div>`).join('')||'<span class="muted">لا توجد طلبات</span>'}</div></div>`;
 el('addProduct').onclick=addProduct;el('addCodes').onclick=addCodes;el('saveNumbers').onclick=saveNumbers;document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>editProduct(b.dataset.editProduct,plist));document.querySelectorAll('[data-toggle-product]').forEach(b=>b.onclick=()=>toggleProduct(b.dataset.toggleProduct,b.dataset.active==='true'));document.querySelectorAll('[data-delete-code]').forEach(b=>b.onclick=()=>deleteCode(b.dataset.deleteCode));document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>reviewTopup(b.dataset.approve,true));document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>reviewTopup(b.dataset.reject,false));}
async function addProduct(){const name=el('pn').value.trim(),category=el('pc').value.trim()||'رقمي',price=Number(el('pp').value),description=el('pd').value.trim();if(!name||!(price>=0))return alert('أدخل اسم المنتج والسعر');const r=await sb.from('products').insert({name,category,price,description,active:true}).select().single();if(r.error)return alert(r.error.message);alert('تمت إضافة المنتج');renderAdmin()}
async function editProduct(id,list){const p=list.find(x=>x.id===id);if(!p)return;const name=prompt('اسم المنتج',p.name);if(name===null)return;const priceText=prompt('السعر بالدينار',p.price);if(priceText===null)return;const price=Number(priceText);if(!name.trim()||!(price>=0))return alert('بيانات غير صحيحة');const category=prompt('التصنيف',p.category||'رقمي');if(category===null)return;const description=prompt('الوصف',p.description||'');if(description===null)return;const r=await sb.from('products').update({name:name.trim(),price,category:category.trim()||'رقمي',description:description.trim()}).eq('id',id);if(r.error)return alert(r.error.message);renderAdmin()}
async function toggleProduct(id,active){const r=await sb.from('products').update({active:!active}).eq('id',id);if(r.error)return alert(r.error.message);renderAdmin()}
async function addCodes(){const productId=el('codeProduct').value;const raw=el('codesText').value;const codes=[...new Set(raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean))];if(!productId||!codes.length)return alert('اختر المنتج وأدخل كودًا واحدًا على الأقل');el('codeMsg').textContent=`جارٍ حفظ ${codes.length} كود...`;let ok=0,fail=0;for(const code of codes){const r=await sb.rpc('admin_upsert_product_code',{p_product_id:productId,p_code:code});if(r.error)fail++;else ok++}el('codeMsg').textContent=`تم حفظ ${ok} كود${fail?`، وتعذر حفظ ${fail}`:''}.`;if(ok)el('codesText').value='';renderAdmin()}
async function deleteCode(id){if(!confirm('حذف هذا الكود من المخزون؟'))return;const r=await sb.rpc('admin_delete_product_code',{p_code_id:id});if(r.error)return alert(r.error.message);renderAdmin()}
async function saveNumbers(){const a=el('libyanaNum').value.trim(),b=el('almadarNum').value.trim();const r1=await sb.rpc('admin_set_setting',{p_key:'libyana_number',p_value:a}),r2=await sb.rpc('admin_set_setting',{p_key:'almadar_number',p_value:b});if(r1.error||r2.error)return alert((r1.error||r2.error).message);alert('تم حفظ أرقام الشحن');renderAdmin()}
async function reviewTopup(id,approve){const note=prompt(approve?'ملاحظة الاعتماد (اختياري)':'سبب الرفض (اختياري)')||'';const r=await sb.rpc('review_wallet_topup',{p_topup_id:id,p_approve:approve,p_note:note});if(r.error)return alert(r.error.message);renderAdmin()}
boot();